/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package overtimemanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static overtimemanagement.Fieldsdata.autocapitalizefirstletter;
import static overtimemanagement.Fieldsdata.onlyint;
import static overtimemanagement.ReadWrite.WriteToFile;
import static overtimemanagement.ReadWrite.userid;

/**
 *
 * @author User
 */
public class AddNewUser extends javax.swing.JPanel {

    public char[] Pa;
    public String ID;
    public String date;

    Connection conn = new DBconnect().connect();
    Statement stmt = null;

    /**
     * Creates new form AddNewUser
     */
    public AddNewUser() {
        initComponents();

        load();

    }

    private void load() {
        //Add Departments to Combobox
        dept.removeAllItems();
        dept.addItem("Select Department");
        dept.addItem("Accounts");
        dept.addItem("Admin");
        dept.addItem("Project Manager");
        dept.addItem("Technician");

        //Add autogenerated ID
        id.setVisible(false);
        idd.setVisible(false);
        ID = userid("userID.txt");
        id.setText(ID);

        //Place Current Date 
        date = DateTime.getTodayDate();
        dat.setText(date);

        //reset all fields
        fname.setText("First");
        lname.setText("Last");
        sal.setText("");
        ph.setText("");
        em.setText("");
        user.setText("");
        pas.setText("");

    }

    private void GetDatathenCheckandWrite() {
        //Get DATA from fields
        String email = em.getText();
        Email useremail = new Email(email);
        String valid = useremail.validateEmailAddress();
        String firstname = fname.getText();
        String lastname = lname.getText();
        String phone = ph.getText();
        String salary = sal.getText();
        String username = user.getText();
        String department = "" + dept.getSelectedItem();
        String fingerprint = fing.getText();
        Pa = pas.getPassword();
        String Password = "";
        System.out.println(Password);
        for (int i = 0; i < Pa.length; i++) {
            Password += Pa[i];
        }
        String data = ID + "," + firstname + "," + lastname + "," + department + "," + salary + "," + phone + "," + email + "," + username + "," + Password + "," + fingerprint;

        //Check Validity
        if (firstname.equals("") || firstname.equals("First")) {
            JOptionPane.showMessageDialog(null, "First name is required");
        }
        if (lastname.equals("") || lastname.equals("Last")) {
            JOptionPane.showMessageDialog(null, "Last name is required");
        } else if (department.equals("Select Department")) {
            JOptionPane.showMessageDialog(null, "Department needs to be selected");
        } else if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Phone no. is required");
        } else if (salary.equals("")) {
            JOptionPane.showMessageDialog(null, "Salary is required");
        } else if (valid.equals("Invalid Email Address")) {
            JOptionPane.showMessageDialog(null, valid);
        } else if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "Username is required");
        } else if (Password.equals("")) {
            JOptionPane.showMessageDialog(null, "Password is required");
        } else {

            //Write
            WriteToFile("userfile.txt", "userID.txt", data, ID);

            //Reload Panel
            load();

        }

    }

    private void GetDatathenCheckandWriteDatabase() {
        //Get DATA from fields
        String email = em.getText();
        Email useremail = new Email(email);
        String valid = useremail.validateEmailAddress();
        String firstname = fname.getText();
        String lastname = lname.getText();
        String phone = ph.getText();
        String salary = sal.getText();
        String username = user.getText();
        String department = "" + dept.getSelectedItem();
        String fingerprint = fing.getText();
        Pa = pas.getPassword();
        String Password = "";
        System.out.println(Password);
        for (int i = 0; i < Pa.length; i++) {
            Password += Pa[i];
        }
        String data = ID + "," + firstname + "," + lastname + "," + department + "," + salary + "," + phone + "," + email + "," + username + "," + Password + "," + fingerprint;

        //Check Validity
        if (firstname.equals("") || firstname.equals("First")) {
            JOptionPane.showMessageDialog(null, "First name is required");
        }
        if (lastname.equals("") || lastname.equals("Last")) {
            JOptionPane.showMessageDialog(null, "Last name is required");
        } else if (department.equals("Select Department")) {
            JOptionPane.showMessageDialog(null, "Department needs to be selected");
        } else if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Phone no. is required");
        } else if (salary.equals("")) {
            JOptionPane.showMessageDialog(null, "Salary is required");
        } else if (valid.equals("Invalid Email Address")) {
            JOptionPane.showMessageDialog(null, valid);
        } else if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "Username is required");
        } else if (Password.equals("")) {
            JOptionPane.showMessageDialog(null, "Password is required");
        } else {
            //Write
            try {
                PreparedStatement pa = conn.prepareStatement("insert into users(Firstname,Lastname,Department,Salary,Phone,Email,username,password,Fingerprint) values (?,?,?,?,?,?,?,?,?)");

                pa.setString(1, firstname);
                pa.setString(2, lastname);
                pa.setString(3, department);
                pa.setString(4, salary);
                pa.setString(5, phone);
                pa.setString(6, email);
                pa.setString(7, username);
                pa.setString(8, Password);
                pa.setString(9, fingerprint);

                int i = pa.executeUpdate();

                if (i > 0) {
                    JOptionPane.showMessageDialog((null), "saved");
                } else {
                    JOptionPane.showMessageDialog((null), "notsaved");

                }
            } catch (SQLException se) {
                //Handle errors for JDBC
                se.printStackTrace();
            } catch (Exception e) {
                //Handle errors for Class.forName
                e.printStackTrace();
            }
            //Reload Panel
            load();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dept = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        idd = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        ph = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dat = new javax.swing.JLabel();
        pas = new javax.swing.JPasswordField();
        fing = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Add User");

        jLabel2.setText("Name");

        fname.setText("First");
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnameMouseClicked(evt);
            }
        });

        jLabel4.setText("Department");

        jLabel5.setText("Fingerprint");

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        id.setText("Autogenerated");

        idd.setText("ID");

        lname.setText("Last");
        lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnameFocusLost(evt);
            }
        });
        lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnameMouseClicked(evt);
            }
        });

        ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phKeyTyped(evt);
            }
        });

        jLabel7.setText("Phone No.");

        jLabel8.setText("Email Address");

        jLabel9.setText("Username");

        jLabel10.setText("Password");

        sal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salKeyTyped(evt);
            }
        });

        jLabel11.setText("Salary(dh)");

        dat.setText("Current Date");

        fing.setText("Undecided");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(555, 555, 555)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(idd)
                .addGap(18, 18, 18)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(526, 526, 526)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel11))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel9))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fing, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dat)
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(41, 41, 41)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 174, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        GetDatathenCheckandWriteDatabase();

    }//GEN-LAST:event_saveActionPerformed

    private void phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phKeyTyped
        onlyint(evt);
    }//GEN-LAST:event_phKeyTyped

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        autocapitalizefirstletter(fname);
    }//GEN-LAST:event_fnameFocusLost

    private void lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusLost
        autocapitalizefirstletter(lname);
    }//GEN-LAST:event_lnameFocusLost

    private void fnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseClicked
        String firstname = fname.getText();
        if (firstname.equals("First")) {
            fname.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_fnameMouseClicked

    private void lnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnameMouseClicked
        String lastname = lname.getText();
        if (lastname.equals("Last")) {
            lname.setText("");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_lnameMouseClicked

    private void salKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salKeyTyped
        onlyint(evt);     // TODO add your handling code here:
    }//GEN-LAST:event_salKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dat;
    private javax.swing.JComboBox dept;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fing;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pas;
    private javax.swing.JTextField ph;
    private javax.swing.JTextField sal;
    private javax.swing.JButton save;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
