/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package overtimemanagement;


/**
 *
 * @author User
 */
public class OvertimePayments extends javax.swing.JPanel {

    /**
     * Creates new form OvertimePayments
     */
    public OvertimePayments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        res = new javax.swing.JTable();
        l2 = new javax.swing.JLabel();
        searchBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        l7 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        l8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        l9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        searchBut1 = new javax.swing.JButton();
        searchBut2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        res.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(res);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 860, 210));

        l2.setText("Date");
        add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, 20));

        searchBut.setText("Scan");
        searchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButActionPerformed(evt);
            }
        });
        add(searchBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 760, 110, 40));

        jLabel3.setText("Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 5, -1, -1));

        date.setText("Time");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 0, 104, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Overtime Payments");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 6, -1, -1));

        l3.setText("Amt to be Paid");
        add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, -1, 20));

        l4.setText("Hours");
        add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, -1));

        jRadioButton1.setText("Paid");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 830, -1, -1));

        jRadioButton2.setText("Unpaid");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 830, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 60, -1));

        l5.setText("From");
        add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, 20));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 60, -1));

        l6.setText("To");
        add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, 20));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 60, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 60, -1));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 79, -1));

        jLabel11.setText("Salary");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, -1, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 79, -1));

        jLabel7.setText("Phone No.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, -1, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 79, -1));

        jLabel8.setText("Email Address");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 60, -1));
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 60, -1));

        l7.setText("Project");
        add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, 20));
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 60, -1));

        l8.setText("Project Manager");
        add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 450, 20));

        l9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        l9.setText("Overtime Information");
        add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Personal Information");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        l1.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        l1.setText("Name of Technician");
        add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 180, 30));

        jCheckBox1.setText("Approved by Director");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 720, -1, -1));

        searchBut1.setText("Save");
        searchBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBut1ActionPerformed(evt);
            }
        });
        add(searchBut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 910, 270, 70));

        searchBut2.setText("Print");
        searchBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBut2ActionPerformed(evt);
            }
        });
        add(searchBut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 110, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, 190));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Preview before Printing\n");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 450, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void searchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButActionPerformed
      
    }//GEN-LAST:event_searchButActionPerformed

    private void searchBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBut1ActionPerformed

    private void searchBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBut2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTable res;
    private javax.swing.JButton searchBut;
    private javax.swing.JButton searchBut1;
    private javax.swing.JButton searchBut2;
    // End of variables declaration//GEN-END:variables
}
